// Generated by Wrangler on Mon Sep 09 2024 16:49:36 GMT-0600 (Mountain Daylight Time)
// by running `wrangler types`

// biome-ignore lint/complexity/noBannedTypes: This is a generated file, so we can't avoid banned types.
type Env = {};
